name: Deploy images to image GHCR
on:
  push:
    branches:
      - main

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: 'Checkout Github Action'
        uses: action/checkout@v4
      - name: 'Login to Github container registry'
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrects.GITHUB_TOKEN }}
      - name: 'Build and push the image'
        run: |
          docker build . -- tag  gchr.io/${{ github.repository_owner }}/hello:latest
          docker push gchr.io/${{ github.repository_owner }}/hello:latest
        
